---
title: Starred
timezone: Europe/Amsterdam
collections:
  clients:
    title: Clients
    output: false
    path: ''
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: false
    path: ''
  testimonials:
    title: Testimonials
    output: true
    permalink: "/:collection/:title.html"
    path: ''
  uploads:
    title: Uploads
    output: true
email: support@starred.com
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
languages:
- en
- nl
exclude_from_localizations:
- js
- images
- styles
- _team
- _testimonials
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    Server: localhost:4000
markdown: kramdown
gems:
- jekyll-feed
- jekyll-multiple-languages-plugin
- jekyll-sitemap
exclude:
- Gemfile.lock
- package.json
- node_modules
- gulpfile.js
- package.json
- src
